/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SnapRouteImport } from './routes/snap'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as TrackingIdRouteImport } from './routes/tracking.$id'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as AuthenticatedProviderDashboardRouteImport } from './routes/_authenticated/provider-dashboard'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ServicesCategoryIndexRouteImport } from './routes/services.$category.index'
import { Route as ServicesCategoryServiceRouteImport } from './routes/services.$category.$service'
import { Route as AuthenticatedJobIdRouteImport } from './routes/_authenticated/job.$id'

const SnapRoute = SnapRouteImport.update({
  id: '/snap',
  path: '/snap',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const TrackingIdRoute = TrackingIdRouteImport.update({
  id: '/tracking/$id',
  path: '/tracking/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProviderDashboardRoute =
  AuthenticatedProviderDashboardRouteImport.update({
    id: '/provider-dashboard',
    path: '/provider-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ServicesCategoryIndexRoute = ServicesCategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCategoryServiceRoute = ServicesCategoryServiceRouteImport.update({
  id: '/$category/$service',
  path: '/$category/$service',
  getParentRoute: () => ServicesRoute,
} as any)
const AuthenticatedJobIdRoute = AuthenticatedJobIdRouteImport.update({
  id: '/job/$id',
  path: '/job/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/categories': typeof CategoriesRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/snap': typeof SnapRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/provider-dashboard': typeof AuthenticatedProviderDashboardRoute
  '/provider/$id': typeof ProviderIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/services/': typeof ServicesIndexRoute
  '/job/$id': typeof AuthenticatedJobIdRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/services/$category/': typeof ServicesCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/categories': typeof CategoriesRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/snap': typeof SnapRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/provider-dashboard': typeof AuthenticatedProviderDashboardRoute
  '/provider/$id': typeof ProviderIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/services': typeof ServicesIndexRoute
  '/job/$id': typeof AuthenticatedJobIdRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/services/$category': typeof ServicesCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/book': typeof BookRoute
  '/categories': typeof CategoriesRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/snap': typeof SnapRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/provider-dashboard': typeof AuthenticatedProviderDashboardRoute
  '/provider/$id': typeof ProviderIdRoute
  '/tracking/$id': typeof TrackingIdRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/job/$id': typeof AuthenticatedJobIdRoute
  '/services/$category/$service': typeof ServicesCategoryServiceRoute
  '/services/$category/': typeof ServicesCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/categories'
    | '/emergency'
    | '/history'
    | '/login'
    | '/register'
    | '/search'
    | '/services'
    | '/snap'
    | '/dashboard'
    | '/provider-dashboard'
    | '/provider/$id'
    | '/tracking/$id'
    | '/services/'
    | '/job/$id'
    | '/services/$category/$service'
    | '/services/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/categories'
    | '/emergency'
    | '/history'
    | '/login'
    | '/register'
    | '/search'
    | '/snap'
    | '/dashboard'
    | '/provider-dashboard'
    | '/provider/$id'
    | '/tracking/$id'
    | '/services'
    | '/job/$id'
    | '/services/$category/$service'
    | '/services/$category'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/book'
    | '/categories'
    | '/emergency'
    | '/history'
    | '/login'
    | '/register'
    | '/search'
    | '/services'
    | '/snap'
    | '/_authenticated/dashboard'
    | '/_authenticated/provider-dashboard'
    | '/provider/$id'
    | '/tracking/$id'
    | '/services/'
    | '/_authenticated/job/$id'
    | '/services/$category/$service'
    | '/services/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BookRoute: typeof BookRoute
  CategoriesRoute: typeof CategoriesRoute
  EmergencyRoute: typeof EmergencyRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SnapRoute: typeof SnapRoute
  ProviderIdRoute: typeof ProviderIdRoute
  TrackingIdRoute: typeof TrackingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/snap': {
      id: '/snap'
      path: '/snap'
      fullPath: '/snap'
      preLoaderRoute: typeof SnapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/tracking/$id': {
      id: '/tracking/$id'
      path: '/tracking/$id'
      fullPath: '/tracking/$id'
      preLoaderRoute: typeof TrackingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provider-dashboard': {
      id: '/_authenticated/provider-dashboard'
      path: '/provider-dashboard'
      fullPath: '/provider-dashboard'
      preLoaderRoute: typeof AuthenticatedProviderDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/services/$category/': {
      id: '/services/$category/'
      path: '/$category'
      fullPath: '/services/$category/'
      preLoaderRoute: typeof ServicesCategoryIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$category/$service': {
      id: '/services/$category/$service'
      path: '/$category/$service'
      fullPath: '/services/$category/$service'
      preLoaderRoute: typeof ServicesCategoryServiceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/_authenticated/job/$id': {
      id: '/_authenticated/job/$id'
      path: '/job/$id'
      fullPath: '/job/$id'
      preLoaderRoute: typeof AuthenticatedJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProviderDashboardRoute: typeof AuthenticatedProviderDashboardRoute
  AuthenticatedJobIdRoute: typeof AuthenticatedJobIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProviderDashboardRoute: AuthenticatedProviderDashboardRoute,
  AuthenticatedJobIdRoute: AuthenticatedJobIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServicesRouteChildren {
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesCategoryServiceRoute: typeof ServicesCategoryServiceRoute
  ServicesCategoryIndexRoute: typeof ServicesCategoryIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesCategoryServiceRoute: ServicesCategoryServiceRoute,
  ServicesCategoryIndexRoute: ServicesCategoryIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BookRoute: BookRoute,
  CategoriesRoute: CategoriesRoute,
  EmergencyRoute: EmergencyRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SnapRoute: SnapRoute,
  ProviderIdRoute: ProviderIdRoute,
  TrackingIdRoute: TrackingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
